### PR TITLE
parse perPage prop

### LINKED ISSUE #31: perPage attribute does not work
https://svelte.dev/repl/bc764e128fc24a10950a1c51973a25fd?version=3.22.3

It seems siema doesn't accept the perPage parameter as an string. If I change the number or introduce a parseInt on the svelte-carousel code before passing the prop to siema it works.

### PR DESCRIPTION
**Pull request by jokin**
Fixes #31

### CODE REVIEW

File: src/Carousel.svelte [hunk 1]
```diff
@@ -104,7 +104,7 @@
 	onMount(() => {
 		controller = new Siema({
 			selector: siema,
-			perPage,
+			perPage: isNaN(perPage)? perPage: Number(perPage),
```
Comment (antony) [inline src/Carousel.svelte:107]: What's the purpose of checking `perPage` using `isNaN`?

I feel like this is defensive code when, if people try to pass a non-number, then we should just let the code error.

For instance, what if they pass a string like `foo`? We just want to try to parse it and throw, right?

Comment (jokin) [reply src/Carousel.svelte:107]: Well, they can pass a responsive object({
  perPage: {
    800: 2, // 2 items for viewport wider than 800px
    1240: 3 // 3 items for viewport wider than 1240px
  })
, and should not fail, so it seemed the more straightforward to let both cases being handled.  
 other way could be check if is an string and in that case use parseInt.

Really the original problem comes from html attributes, that are string by default, if instead of setting the perPage directly, you define a number variable in javascript and bind the prop to that variable it works also correctly.

Comment (antony) [reply src/Carousel.svelte:107]: Ah right.

So I think we should probably handle this by saying `typeof perPage === 'object' ? perPage : Number(perPage)` - what do you reckon?

Comment (jokin) [reply src/Carousel.svelte:107]: Yeah, no problem, I will update the pull request

**Comment by jokin** [comment]
I, do you have the chance to verify this so I can base another pull request from here?
